version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
general:
  branches:
    only:
      - new
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: circleci/php:7.2-cli-stretch
        environment:
          APP_ENV: test
    steps:
      - checkout
      - run:
          name: Update Composer
          command: sudo composer self-update
      - run:
          name: Install PHP extensions
          command: |
            sudo pecl install ast
            sudo docker-php-ext-enable ast
      - run:
          name: Disable xdebug
          command: |
            sudo sed -i 's/^zend_extension/;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - run:
          name: Display PHP information
          command: |
            php -v
            php -m
            composer --version
      - restore_cache: # special step to restore the dependency cache if `composer.lock` does not change
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v1-
      - run:
          name: Install project dependencies
          command: composer install --prefer-dist --optimize-autoloader
      - save_cache: # special step to save the dependency cache with the `composer.lock` cache key template
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: Run Unit tests
          command: |
            composer validate
            phpdbg -qrr vendor/bin/phpunit --coverage-clover=build/coverage.xml
      - run:
          name: Run PHP-Stan
          command: |
            composer phpstan
      - run:
          name: Run Phan
          command: |
            composer phan
      - store_artifacts:
          path: build/coverage.xml
      - codecov/upload:
          file: build/coverage.xml
